# Generated by Django 5.2.3 on 2025-06-25 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0005_chatthread_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="thread_id",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
