# Generated by Django 5.2.3 on 2025-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0006_chatthread_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="state",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="state",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
