# Generated by Django 5.2.3 on 2025-07-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0008_remove_useranswer_question_remove_useranswer_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onboardinganswer",
            unique_together=set(),
        ),
    ]
