# Generated by Django 5.2.3 on 2025-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0010_alter_instagrampost_media_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrampost",
            name="media_url",
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="post_url",
            field=models.URLField(max_length=2500),
        ),
    ]
