# Generated by Django 5.2.3 on 2025-07-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0011_alter_instagrampost_media_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique identifier like 'CAROUSEL_SYSTEM_PROMPT'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="The actual prompt text used in the system."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description or usage note.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
