# Generated by Django 5.2.3 on 2025-07-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0012_systemprompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemprompt",
            name="description",
        ),
        migrations.RemoveField(
            model_name="systemprompt",
            name="prompt_text",
        ),
        migrations.RemoveField(
            model_name="systemprompt",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="systemprompt",
            name="content",
            field=models.TextField(
                default="You are a helpful assistant.",
                help_text="System prompt text used in AI interactions.",
            ),
        ),
        migrations.AddField(
            model_name="systemprompt",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="systemprompt",
            name="name",
            field=models.CharField(default="default", max_length=100, unique=True),
        ),
    ]
