# Generated by Django 5.2.3 on 2025-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0013_remove_systemprompt_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagram_user",
            name="media_url",
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
