# Generated by Django 5.2.3 on 2025-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0014_instagram_user_media_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagram_user",
            name="is_insta_api",
            field=models.BooleanField(default=False),
        ),
    ]
